"""
Protocol (interface) for dating platform adapters (Tinder, Bumble, etc.).
Platform-specific sessions use a BrowserSession from core and delegate
all actions to an adapter implementing this protocol.
"""
from typing import Protocol, Any, List, Optional


class DatingProfile(Protocol):
    """Minimal profile interface: name, age, bio, images, etc. (platform-specific impl)."""
    def get_name(self) -> Optional[str]: ...
    def get_age(self) -> Optional[int]: ...
    def get_bio(self) -> Optional[str]: ...
    def get_image_urls(self) -> Optional[List[str]]: ...
    def get_id(self) -> str: ...
    def get_genders(self) -> Optional[List[str]]: ...
    def get_passions(self) -> Any: ...
    def get_lifestyle(self) -> Any: ...
    def get_basics(self) -> Any: ...
    def get_looking_for(self) -> Optional[str]: ...


class PlatformAdapter(Protocol):
    """Contract for TinderAdapter, BumbleAdapter, etc."""

    def handle_popups(self) -> Optional[str]:
        """Handle modals/popups; return description if one was dismissed, else None."""
        ...

    def is_logged_in(self) -> bool:
        """True if the app is in logged-in state (e.g. app/recs)."""
        ...

    # Auth
    def login_using_google(self, email: str, password: str) -> Optional[str]: ...
    def login_using_facebook(self, email: str, password: str) -> Optional[str]: ...
    def login_using_sms(self, country: str, phone_number: str) -> Optional[str]: ...

    # Discovery
    def like(self) -> bool:
        """Perform like action. Returns True if like was sent."""
        ...
    def dislike(self) -> None: ...
    def superlike(self) -> None: ...

    def get_current_profile(
        self,
        quickload: bool = True,
        browse_photos: int = 1,
        browse_photos_delay: float = 0.2,
    ) -> Optional[Any]:
        """Return current profile (platform-specific: Geomatch, BumbleProfile, etc.)."""
        ...

    def close_profile(self) -> None:
        """Close open profile and return to discovery."""
        ...

    # Preferences (optional; Bumble may have different API)
    def set_distance_range(self, km: int) -> None: ...
    def set_age_range(self, min_age: int, max_age: int) -> None: ...
    def set_sexuality(self, type: Any) -> None: ...
    def set_global(self, boolean: bool) -> None: ...

    # Profile edit (optional)
    def set_bio(self, bio: str) -> None: ...
    def add_photo(self, filepath: str) -> None: ...

    # Matches & messages
    def get_chat_ids(self, new: bool = True, messaged: bool = True) -> List[str]: ...
    def get_new_matches(self, amount: int = 100000, quickload: bool = True) -> List[Any]: ...
    def get_messaged_matches(self, amount: int = 100000, quickload: bool = True) -> List[Any]: ...
    def send_message(self, chatid: str, message: str) -> None: ...
    def send_gif(self, chatid: str, gifname: str) -> None: ...
    def send_song(self, chatid: str, songname: str) -> None: ...
    def send_socials(self, chatid: str, media: Any) -> None: ...
    def unmatch(self, chatid: str) -> None: ...
